#!/usr/bin/env bash
# Render the winget singleton manifest for a release from GoReleaser's
# checksums.txt, so versions, URLs and hashes are never hand-edited.
#
#   scripts/winget-manifest.sh <tag> <checksums.txt> [output-file]
#
# Archive names follow GoReleaser's default template
# (freshen_<version>_windows_<arch>.zip) and the executable sits at the
# archive root (.goreleaser.yaml: archives.wrap_in_directory: false).
set -euo pipefail

if [[ $# -lt 2 || $# -gt 3 ]]; then
  echo "usage: $0 <tag> <checksums.txt> [output-file]" >&2
  exit 2
fi

tag=$1
checksums=$2
out=${3:-}
version=${tag#v}
repo=${GITHUB_REPOSITORY:-seankoji-com/freshen}
base="https://github.com/${repo}/releases/download/${tag}"

sha256_of() {
  local sum
  sum=$(awk -v f="$1" '$2 == f { print $1 }' "$checksums")
  if [[ ! $sum =~ ^[0-9a-f]{64}$ ]]; then
    echo "no sha256 for $1 in $checksums" >&2
    return 1
  fi
  printf '%s' "$sum"
}

x64="freshen_${version}_windows_amd64.zip"
arm64="freshen_${version}_windows_arm64.zip"
x64_sum=$(sha256_of "$x64")
arm64_sum=$(sha256_of "$arm64")

render() {
  cat <<MANIFEST
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.singleton.1.9.0.schema.json
# Generated by scripts/winget-manifest.sh from the release's checksums.txt. Do not edit.
PackageIdentifier: SeanKoji.Freshen
PackageVersion: ${version}
PackageName: freshen
Publisher: Sean Koji
PublisherUrl: https://github.com/seankoji-com
PackageUrl: https://github.com/${repo}
License: Apache-2.0
LicenseUrl: https://github.com/${repo}/blob/main/LICENSE
ShortDescription: High-performance interactive TUI dashboard for multi-repo git management and sync
Moniker: freshen
Tags:
  - git
  - tui
  - cli
InstallerType: zip
NestedInstallerType: portable
Installers:
  - Architecture: x64
    NestedInstallerFiles:
      - RelativeFilePath: freshen.exe
        PortableCommandAlias: freshen
    InstallerUrl: ${base}/${x64}
    InstallerSha256: ${x64_sum}
  - Architecture: arm64
    NestedInstallerFiles:
      - RelativeFilePath: freshen.exe
        PortableCommandAlias: freshen
    InstallerUrl: ${base}/${arm64}
    InstallerSha256: ${arm64_sum}
ManifestType: singleton
ManifestVersion: 1.9.0
MANIFEST
}

if [[ -n $out ]]; then
  render >"$out"
else
  render
fi
